# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Luxembourg Tech School
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
    The Luxembourg Tech School (LTS for short) is a new extracurricular school concept to support the development of future Digital Leaders. It is aimed at 15-20 years old students who are passionate about the digital realm and eager to learn and apply technology in a real business context.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

sendform_token: 36185a41482185052c0b891d07b59072

# Build settings
markdown: kramdown
